version: "3.8"

services:

    backend:
        image: quewinbridger/edgepetrol-sre-challenge:latest-edgepetrol-sre-challenge
            
        command: [sh, -c, "poetry install && poetry run python manage.py makemigrations && poetry run python manage.py migrate && poetry run python manage.py runserver  0.0.0.0:8000"]
   

        ports:
            - 8000:8000
        networks:
            - docker-network
            
        environment:
            - DEBUG=1
networks:
  docker-network:
    driver: bridge
